version: '3.9'
services:
    bd:
        image: mysql
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
           MYSQL_DATABASE: ControlTec
           MYSQL_ROOT_USER: root
           MYSQL_ROOT_PASSWORD: 102025fe

           volumes:
            - ./sql:/docker-entrypoint-initdb.d
        ports:
          - "3308:3306"
    adminer:
      image: adminer
      container_name: adminer
      restart: always
      ports:
        - 8080:8080

    controltec:
        image: luiz0809/controltec-app:1.2
        container_name: controltec
        command: java -jar ControlTecCMD-1.0-SNAPSHOT-jar-with-dependencies.jar





