version: '3.9'
services:
    bd:
        image: mysql:8.0
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
           MYSQL_DATABASE: ControlTec
           MYSQL_ROOT_USER: root
           MYSQL_ROOT_PASSWORD: 102025fe
        networks:
          - compose-bridge
        ports:
          - "3306:3306"
        expose: 
          - "3306"

    controltec:
        image: luiz0809/controltec-app:1.2
        container_name: controltec
        networks:
          - compose-bridge

networks:
    compose-bridge:
        driver: bridge
